# Generated by Django 2.2.4 on 2019-08-23 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('contact', models.TextField(blank=True, verbose_name='Contact')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
            ],
            options={
                'ordering': ['-start', '-end', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebelstuff.Booking')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebelstuff.Stuff')),
            ],
        ),
    ]
