# Generated by Django 2.2.4 on 2019-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebelstuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start', '-end', 'status', 'name']},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('delivered', 'delivered'), ('returned', 'returned')], default='waiting', max_length=16, verbose_name='Status'),
        ),
    ]
