# Generated by Django 2.2.4 on 2019-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebelstuff', '0002_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
