# Generated by Django 3.0 on 2020-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebelstuff', '0003_stuff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Remaining'),
            preserve_default=False,
        ),
    ]
